tab_spaces = 2
where_single_line = true
group_imports = "One"
imports_granularity = "Crate"
use_small_heuristics = "Max"


format_macro_matchers = true
format_macro_bodies = true
reorder_impl_items = true
unstable_features = true