[package]
name = "neko_cron"
version = "1.0.0"
edition.workspace = true
license.workspace = true

[dependencies]
# local crates
neko_core.workspace = true
# external crates
tokio-cron-scheduler.workspace = true
