[package]
name = "neko_proc"
version = "0.0.0"
edition.workspace = true
license.workspace = true

[lib]
path = "src/module.rs"
proc-macro = true

[dependencies]
darling = "0.20"
syn = "2"
proc-macro2 = "1"
quote = "1"