[package]
name = "neko_poise"
version = "0.0.0"
edition.workspace = true
license.workspace = true

[dependencies]
neko_core.workspace = true
neko_fluent.workspace = true
# external crates
poise.workspace = true
unicode-truncate.workspace = true
