[package]
name = "neko_core"
version = "0.0.0"
edition.workspace = true
license.workspace = true

[lib]
path = "src/framework.rs"

[dependencies]
futures.workspace = true
tokio.workspace = true
log.workspace = true
