[package]
name = "neko_fluent"
version = "1.0.0"
edition.workspace = true
license.workspace = true

[lib]
path = "src/module.rs"

[dependencies]
neko_core.workspace = true
# external crates
fluent.workspace = true
intl-memoizer.workspace = true
rust-embed.workspace = true
