[package]
name = "neko_axum"
version = "0.0.0"
edition.workspace = true
license.workspace = true

[lib]
path = "src/module.rs"

[dependencies]
neko_core.workspace = true
# external crates
axum.workspace = true
