[package]
name = "neko_reqwest"
version = "1.0.0"
edition.workspace = true
license.workspace = true

[lib]
path = "src/module.rs"

[dependencies]
neko_core.workspace = true
# external crates
reqwest.workspace = true
